In [1]:
import numpy as np
import time 

In [8]:
# numpy routine to allocate the numbers to array 
a = np.zeros(10)
a.shape

b = np.random.random_sample(10)
b

array([0.58667392, 0.75076538, 0.80258571, 0.94828114, 0.39912979,
       0.9329897 , 0.98519924, 0.0787351 , 0.19931328, 0.33429931])

In [13]:
a = np.arange(6); print(a)
b= np.random.rand(4); print(b)

[0 1 2 3 4 5]
[0.18501219 0.48273349 0.60487016 0.60747611]


In [14]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]
